services:
  - type: web
    name: ethical-url-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PORT
        generateValue: true
